export enum MarketPhase {
  PRE_MARKET = 'PRE_MARKET',
  OPEN_VOLATILITY = 'OPEN_VOLATILITY',
  TRENDING_BULL = 'TRENDING_BULL',
  TRENDING_BEAR = 'TRENDING_BEAR',
  SIDEWAYS = 'SIDEWAYS',
  NEWS_SPIKE = 'NEWS_SPIKE',
  CLOSING = 'CLOSING',
  AFTER_HOURS = 'AFTER_HOURS'
}
